// 模型目录数据模块（从 hmdao-api.mjs 303..1374 迁移）：纯数据 + 两个能力构造 helper。
// 真 ES 导出：MODEL_CATALOG / QWEN3_TTS_VOICES（主文件仍以同名符号使用）。
function createImageCapabilities(overrides = {}) {
  return {
    generationModes: ['textToImage', 'imageToImage', 'inpaint', 'outpaint'],
    referenceRoles: ['style', 'subject', 'element', 'composition', 'lighting', 'omni'],
    toolOperations: [
      'panorama_720',
      'multi_angle_view',
      'pbr_relight',
      'storyboard_grid',
      'hd_toolbox_enhance',
      'hd_upscale',
      'hd_outpaint',
      'hd_inpaint',
      'hd_erase',
      'hd_cutout',
      'hd_crop',
      'hd_restore',
      'smart_grid_split',
      'cinematic_camera_simulation',
    ],
    supportsMultiReference: false,
    supportsOmniReference: false,
    supportsSubjectLock: false,
    supportsCompositionLock: false,
    supportsLightingControl: false,
    supportsConsistencyEnhancement: false,
    supportsIdentityController: false,
    supportsLocalEditing: false,
    supportsRemoteEditing: true,
    supportsStageValidation: true,
    bestFor: [],
    limitations: [],
    ...overrides,
  };
}

function createVideoCapabilities(overrides = {}) {
  return {
    generationModes: [],
    referenceRoles: [],
    toolOperations: [
      'ffmpeg_lossless_trim_wavesurfer',
      'ffmpeg_pixel_crop_cropper',
      'real_cugan_rife_codeformer_enhance',
      'opencv_scenedetect_keyframe_parse',
      'opencv_telea_subtitle_remove',
      'demucs_v4_audio_split',
    ],
    supportsMultiReference: false,
    supportsOmniReference: false,
    supportsSubjectLock: false,
    supportsCompositionLock: false,
    supportsLightingControl: false,
    supportsConsistencyEnhancement: false,
    supportsCameraMotionLockEnhancement: false,
    supportsIdentityController: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsFirstLastFrame: false,
    supportsReferenceVideo: false,
    supportsReferenceImage: false,
    supportsVideoStyleTransfer: false,
    supportsPrimaryVideoMotionLock: false,
    supportsActionTransfer: false,
    supportsLocalEditing: false,
    supportsRemoteEditing: true,
    supportsStageValidation: true,
    bestFor: [],
    limitations: [],
    ...overrides,
  };
}

// Qwen3-TTS-Instruct-Flash 支持的全部音色（非实时指令版；方言音色仅在 qwen3-tts-flash 非指令版）
export const QWEN3_TTS_VOICES = [
  { value: 'Cherry', label: '芊悦·阳光亲切小姐姐', gender: 'female' },
  { value: 'Serena', label: '苏瑶·温柔小姐姐', gender: 'female' },
  { value: 'Ethan', label: '晨煦·阳光温暖男声(北方口音)', gender: 'male' },
  { value: 'Chelsie', label: '千雪·二次元虚拟女友', gender: 'female' },
  { value: 'Momo', label: '茉兔·撒娇搞怪女声', gender: 'female' },
  { value: 'Vivian', label: '十三·拽拽可爱小暴躁', gender: 'female' },
  { value: 'Moon', label: '月白·率性帅气男声', gender: 'male' },
  { value: 'Maia', label: '四月·知性温柔女声', gender: 'female' },
  { value: 'Kai', label: '凯·耳朵SPA男声', gender: 'male' },
  { value: 'Nofish', label: '不吃鱼·不会翘舌音设计师男声', gender: 'male' },
  { value: 'Bella', label: '萌宝·小萝莉女声', gender: 'female' },
  { value: 'Eldric Sage', label: '沧明子·沉稳睿智老者男声', gender: 'male' },
  { value: 'Mia', label: '乖小妹·温顺乖巧女声', gender: 'female' },
  { value: 'Mochi', label: '沙小弥·聪明伶俐小大人男声', gender: 'male' },
  { value: 'Bellona', label: '燕铮莺·声音洪亮御姐女声', gender: 'female' },
  { value: 'Vincent', label: '田叔·沙哑烟嗓男声', gender: 'male' },
  { value: 'Bunny', label: '萌小姬·小萝莉女声', gender: 'female' },
  { value: 'Neil', label: '阿闻·新闻主持人男声', gender: 'male' },
  { value: 'Elias', label: '墨讲师·学科严谨讲师女声', gender: 'female' },
  { value: 'Arthur', label: '徐大爷·质朴嗓音男声', gender: 'male' },
  { value: 'Nini', label: '邻家妹妹·甜美邻家女声', gender: 'female' },
  { value: 'Seren', label: '小婉·温和舒缓助眠女声', gender: 'female' },
  { value: 'Pip', label: '顽屁小孩·调皮童真男声', gender: 'male' },
  { value: 'Stella', label: '少女阿月·迷糊少女女声', gender: 'female' },
];

// Qwen3-TTS-Flash（非指令版）音色 = 上述 24 种基础音色 + 4 种方言音色（粤/沪/京/川）
const QWEN3_TTS_FLASH_DIALECT_VOICES = [
  { value: 'Rocky', label: '粤语男声', gender: 'male' },
  { value: 'Jada', label: '上海话女声', gender: 'female' },
  { value: 'Dylan', label: '北京话男声', gender: 'male' },
  { value: 'Sunny', label: '四川话女声', gender: 'female' },
];
const QWEN3_TTS_FLASH_VOICES = [...QWEN3_TTS_VOICES, ...QWEN3_TTS_FLASH_DIALECT_VOICES];

export const MODEL_CATALOG = [
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    provider: 'deepseek',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: 'General text generation and reasoning.',
    latency: '2s',
    price: 0.02,
    currency: 'CNY',
    discountLabel: 'New user 9x',
    discountPercent: 10,
  },
  {
    id: 'gemini-31',
    name: 'Gemini 3.1',
    provider: 'openai',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: 'OpenAI-compatible multimodal reasoning model routed through relay endpoints.',
    latency: '3s',
    price: 0.08,
    currency: 'USD',
    upstreamModel: 'gemini-3.1',
  },
  {
    id: 'lib-image',
    name: 'Qwen 图片',
    provider: 'siliconflow',
    mode: 'image',
    nodeTypes: ['image'],
    description: '硅基流动托管的 Qwen 原生图片生成',
    latency: '12s',
    price: 0.28,
    currency: 'CNY',
    discountLabel: 'Limited 85x',
    discountPercent: 15,
    upstreamModel: 'Qwen/Qwen-Image',
    capabilities: createImageCapabilities({
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsIdentityController: true,
      bestFor: ['中文海报', '多参考图像生成', '参考主体锁定', '保构图换主体', '全能参数'],
      limitations: ['严格构图锁死弱于专用编辑模型'],
    }),
  },
  {
    id: 'doubao-seedream-5-0-lite',
    name: 'Seedream 5.0 Lite',
    provider: 'volcengine',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'High quality product and scene images with stronger edit routing for multi-reference work.',
    latency: '18s',
    price: 0.36,
    currency: 'CNY',
    upstreamModel: 'doubao-seedream-5.0-lite',
    capabilities: createImageCapabilities({
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      toolOperations: ['multi_angle_view', 'pbr_relight', 'storyboard_grid', 'hd_toolbox_enhance', 'cinematic_camera_simulation'],
      bestFor: ['商品图', '高质感场景', '打光强化', '构图细化', '保构图换主体', '全能参数'],
    }),
  },
  {
    id: 'doubao-seedream-4-5',
    name: 'Seedream 4.5',
    provider: 'volcengine',
    mode: 'image',
    nodeTypes: ['image'],
    description: '火山方舟 Seedream 4.5 图片模型，提供新用户免费额度，适合商品图、场景图与多参考工作流。',
    latency: '18s',
    price: 0.3,
    currency: 'CNY',
    upstreamModel: 'doubao-seedream-4.5',
    discountLabel: '新用户免费',
    discountPercent: 100,
  },
  {
    id: 'doubao-seedream-5-0-pro',
    name: 'Seedream 5.0 Pro',
    provider: 'volcengine',
    mode: 'image',
    nodeTypes: ['image'],
    description: '火山方舟 Seedream 5.0 旗舰图片模型，最高质感与最强语义理解，适合品牌 KV、广告大片与复杂多参考工作流。',
    latency: '22s',
    price: 0.6,
    currency: 'CNY',
    upstreamModel: 'doubao-seedream-5.0-pro',
    capabilities: createImageCapabilities({
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsIdentityController: true,
      toolOperations: ['multi_angle_view', 'pbr_relight', 'storyboard_grid', 'hd_toolbox_enhance', 'cinematic_camera_simulation'],
      bestFor: ['品牌 KV', '广告大片', '高质感商品图', '复杂多参考', '保构图换主体', '全能参考'],
    }),
  },
  {
    id: 'doubao-seedance-2-0',
    name: '豆包 Seedance 2.0',
    provider: 'volcengine',
    mode: 'video',
    nodeTypes: ['video'],
    description: '火山方舟 Seedance 2.0 视频生成模型，支持文生视频、图生视频与首尾帧控制，适合中文商业片、角色参考与镜头延展。',
    latency: '60s',
    price: 2.8,
    currency: 'CNY',
    upstreamModel: 'doubao-seedance-2.0',
    capabilities: createVideoCapabilities({
      generationModes: ['textToVideo', 'imageToVideo', 'firstLastFrame'],
      referenceRoles: ['style', 'subject', 'composition', 'lighting', 'omni'],
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsIdentityController: true,
      supportsTextToVideo: true,
      supportsImageToVideo: true,
      supportsFirstLastFrame: true,
      supportsReferenceImage: true,
      supportsReferenceVideo: false,
      supportsVideoStyleTransfer: false,
      supportsPrimaryVideoMotionLock: false,
      supportsActionTransfer: false,
      bestFor: ['中文商业片', '图生视频', '首尾帧控制', '角色参考', '镜头延展'],
    }),
  },
  {
    id: 'qwen3-tts-instruct',
    name: '通义 Qwen3-TTS-Instruct',
    provider: 'bailian',
    mode: 'audio',
    nodeTypes: ['audio'],
    description: '阿里通义 Qwen3-TTS-Instruct-Flash，新一代指令式语音合成：支持自然语言 instructions 控制情绪/语速/风格，内置 24 种音色，覆盖中英文与多语种，适合高质量配音、有声书与短视频人声。',
    latency: '5s',
    price: 0.03,
    currency: 'CNY',
    upstreamModel: 'qwen3-tts-instruct-flash',
    audioVoices: QWEN3_TTS_VOICES,
    capabilities: {
      generationModes: ['textToAudio', 'voiceClone'],
      supportsTextToAudio: true,
      supportsVoiceClone: true,
      supportsInstructions: true,
      supportsBgm: false,
      bestFor: ['中文 TTS', '高质量配音', '有声书', '多语种', '情绪/风格控制'],
      limitations: ['不生成 BGM/音乐', '方言音色（粤/沪/京/川等）在 qwen3-tts-flash 非指令版，本模型不含'],
    },
  },
  {
    id: 'qwen3-tts-flash',
    name: '通义 Qwen3-TTS-Flash（含方言）',
    provider: 'bailian',
    mode: 'audio',
    nodeTypes: ['audio'],
    description: '阿里通义 Qwen3-TTS-Flash，非指令版语音合成：内置 24 种基础音色 + 粤/沪/京/川 4 种方言音色（Rocky/Jada/Dylan/Sunny），适合方言配音、短视频与多语种人声。',
    latency: '5s',
    price: 0.03,
    currency: 'CNY',
    upstreamModel: 'qwen3-tts-flash',
    audioVoices: QWEN3_TTS_FLASH_VOICES,
    capabilities: {
      generationModes: ['textToAudio', 'voiceClone'],
      supportsTextToAudio: true,
      supportsVoiceClone: true,
      supportsInstructions: false,
      supportsBgm: false,
      bestFor: ['中文 TTS', '方言配音', '有声书', '多语种'],
      limitations: ['不生成 BGM/音乐', '不支持自然语言 instructions 指令（请用 qwen3-tts-instruct）'],
    },
  },
  {
    id: 'doubao-audio-1-0',
    name: '豆包 音频生成 1.0',
    provider: 'volcengine',
    mode: 'audio',
    nodeTypes: ['audio'],
    description: '火山方舟 豆包音频生成 1.0，支持 TTS 语音合成、配音与 BGM 生成，适合中文有声内容、配音与短视频音轨。',
    latency: '8s',
    price: 0.12,
    currency: 'CNY',
    upstreamModel: 'doubao-audio-1.0',
    capabilities: {
      generationModes: ['textToAudio', 'voiceClone'],
      supportsTextToAudio: true,
      supportsVoiceClone: true,
      supportsBgm: true,
      bestFor: ['中文 TTS', '配音', '短视频音轨', '有声内容'],
      limitations: ['不支持视频生成'],
    },
  },
  {
    id: 'minimax-speech-28',
    name: 'MiniMax 语音合成 Speech 2.8',
    provider: 'minimax',
    mode: 'audio',
    nodeTypes: ['audio'],
    description: 'MiniMax 海螺 Speech-2.8-HD，广播级高保真语音合成，原生语气词、强情感控制、多语支持，当前最佳 TTS 之一。',
    latency: '4s',
    price: 0.015,
    currency: 'CNY',
    upstreamModel: 'speech-2.8-hd',
    capabilities: {
      generationModes: ['textToAudio', 'voiceClone'],
      supportsTextToAudio: true,
      supportsVoiceClone: true,
      supportsBgm: false,
      bestFor: ['中文 TTS', '高质量配音', '语音克隆', '多语种'],
      limitations: ['不生成 BGM/音乐'],
    },
  },
  {
    id: 'minimax-music-01',
    name: 'MiniMax 音乐生成 01',
    provider: 'minimax',
    mode: 'audio',
    nodeTypes: ['audio'],
    description: 'MiniMax 音乐生成 01（music-01），文本/歌词生成完整 BGM 与配乐，适合短视频背景音乐、氛围铺底与片头曲。',
    latency: '30s',
    price: 0.08,
    currency: 'CNY',
    upstreamModel: 'music-01',
    capabilities: {
      generationModes: ['music'],
      supportsTextToAudio: false,
      supportsVoiceClone: false,
      supportsBgm: true,
      bestFor: ['BGM', '配乐', '短视频音轨'],
      limitations: ['不支持语音合成'],
    },
  },
  {
    id: 'gpt-image-2',
    name: 'GPT Image 2',
    provider: 'openai',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'OpenAI-compatible image generation and editing through relay endpoints.',
    latency: '14s',
    price: 0.45,
    currency: 'USD',
    upstreamModel: 'gpt-image-2',
    capabilities: createImageCapabilities({
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsIdentityController: true,
      bestFor: ['商品图', '局部改图', '保构图换主体', '多模态图片编辑', '全能参数'],
    }),
  },
  {
    id: 'grok-imagine-1.5-edit-apimart',
    name: 'Grok Imagine 1.5 Edit',
    provider: 'openai',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'Relay-edit image model optimized for instruction-heavy and multi-reference image editing.',
    latency: '18s',
    price: 0.52,
    currency: 'USD',
    upstreamModel: 'grok-imagine-1.5-edit-apimart',
    capabilities: createImageCapabilities({
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsIdentityController: true,
      bestFor: ['复杂编辑', '保构图换主体', '多参考改图', '全能参数'],
    }),
  },
  {
    id: 'gemini-3-pro-image-preview',
    name: 'Gemini 3 Pro Image Preview',
    provider: 'openai',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'OpenAI-compatible relay preview model for multimodal image understanding and draft editing.',
    latency: '15s',
    price: 0.32,
    currency: 'USD',
    upstreamModel: 'gemini-3-pro-image-preview',
    capabilities: createImageCapabilities({
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      bestFor: ['多模态预览', '结构理解', '参考分析', '草案编辑'],
      limitations: ['严格构图锁死弱于专用编辑模型'],
    }),
  },
  {
    id: 'midjourney-relax',
    name: 'Midjourney Relax',
    provider: 'openai',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'Relay-based Midjourney image generation candidate.',
    latency: '20s',
    price: 0.5,
    currency: 'USD',
    upstreamModel: 'midjourney-relax',
    capabilities: createImageCapabilities({
      bestFor: ['风格化创作', '概念图', '海报初稿'],
      limitations: ['多参考主体锁定较弱'],
    }),
  },
  {
    id: 'nano-banana2',
    name: 'Nano Banana 2',
    provider: 'openai',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'Creative relay image model for lightweight visual ideation.',
    latency: '12s',
    price: 0.22,
    currency: 'USD',
    upstreamModel: 'nano-banana2',
    capabilities: createImageCapabilities({
      bestFor: ['创意草图', '轻量商品图', '风格探索'],
    }),
  },
  {
    id: 'flux-pro',
    name: 'FLUX Pro',
    provider: 'fal',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'Poster and photorealistic generation.',
    latency: '20s',
    price: 0.38,
    currency: 'CNY',
    discountLabel: 'Member 88x',
    discountPercent: 12,
    capabilities: createImageCapabilities({
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsIdentityController: true,
      bestFor: ['海报', '写实图像', '角色一致性', '保构图换主体', '全能参数'],
    }),
  },
  {
    id: 'wanx-v1',
    name: '通义万相',
    provider: 'bailian',
    mode: 'image',
    nodeTypes: ['image'],
    description: 'Chinese prompt image generation.',
    latency: '15s',
    price: 0.3,
    currency: 'CNY',
    capabilities: createImageCapabilities({
      toolOperations: ['storyboard_grid', 'hd_toolbox_enhance', 'smart_grid_split'],
      bestFor: ['中文文生图', '轻量图片生成'],
      limitations: ['复杂多参考控制较弱', '严格保构图换主体能力有限'],
    }),
  },
  {
    id: 'wan2.7-image',
    name: '通义万相 2.7 (图生图)',
    provider: 'bailian',
    mode: 'image',
    nodeTypes: ['image'],
    description: '万相 2.7 图像生成与编辑，支持参考图 / 多图参考 / 保构图换主体 / 风格迁移。免费额度内可出图，适合「三维渲染→真实照片」等图生图任务。',
    latency: '20s',
    price: 0,
    currency: 'CNY',
    // 阿里云百炼实际模型 ID；若控制台显示不同（如 wan2.7-image / wan2.7-image-pro）请修正此值
    upstreamModel: 'wanx2.7-image',
    capabilities: createImageCapabilities({
      supportsReferenceImage: true,
      supportsMultiReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      bestFor: ['参考图改图', '保构图换主体', '风格迁移', '图生图', '三维渲染转真实照片'],
      limitations: [],
    }),
  },
  {
    id: 'qwen3.7-plus',
    name: 'Qwen3.7-Plus',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '百炼最新旗舰多模态模型，支持图片/视频深度分析、提示词反推、光影构图风格解析，中文理解领先。',
    latency: '3s',
    price: 0.008,
    currency: 'CNY',
    upstreamModel: 'qwen3.7-plus',
    discountLabel: '新用户免费',
    discountPercent: 100,
  },
  {
    id: 'qwen3.7-flash',
    name: 'Qwen3.7-Flash',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '通义千问 Qwen3.7-Flash 轻量高速多模态模型，支持图文输入、对话与截图识文，延迟低、成本低，作为智能机器人与截图识文的统一默认模型。',
    latency: '2s',
    price: 0.002,
    currency: 'CNY',
    upstreamModel: 'qwen3.7-flash',
    discountLabel: '新用户免费',
    discountPercent: 100,
  },
  {
    id: 'qwen3.8-flash',
    name: 'Qwen3.8-Flash',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '通义千问 Qwen3.8-Flash 轻量高速多模态模型，作为 Qwen3.7-Flash 的备选，延迟更低、成本更优，适合对话与截图识文。',
    latency: '1.5s',
    price: 0.0015,
    currency: 'CNY',
    upstreamModel: 'qwen3.8-flash',
    discountLabel: '新用户免费',
    discountPercent: 100,
  },
  {
    id: 'qwen3.7-vl',
    name: 'Qwen3.7-VL',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '通义千问最新视觉语言旗舰，原生视频/多图理解，适合关键帧语义解析、镜头语言整理与中文分镜脚本。',
    latency: '3s',
    price: 0.008,
    currency: 'CNY',
    upstreamModel: 'qwen-vl-max',
    discountLabel: '新用户免费',
    discountPercent: 100,
  },
  {
    id: 'glm-4v-plus',
    name: 'GLM-4V-Plus',
    provider: 'zhipu',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '智谱最强视觉语言模型，原生视频理解，适合逐帧语义分析、主体识别、运镜拆解与场景推断。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'glm-4v-plus',
  },
  {
    id: 'internvl3-pro',
    name: 'InternVL3 Pro',
    provider: 'siliconflow',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '上海AI实验室 InternVL3 系列，开源视频理解最强，擅长多帧对比、动作时序与长视频语义集成。硅基流动托管。',
    latency: '4s',
    price: 0.004,
    currency: 'CNY',
    upstreamModel: 'Pro/OpenGVLab/InternVL3-78B',
  },
  {
    id: 'doubao-vision-pro',
    name: '豆包视觉 Pro',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '字节跳动视觉语言模型，擅长中文短视频内容理解、电商场景与人物动作识别。',
    latency: '3s',
    price: 0.005,
    currency: 'CNY',
    upstreamModel: 'doubao-vision-pro-32k',
  },
  // ===== 国内聚合平台补登：激活一个平台即解锁其托管的第三方模型 =====
  // 阿里云百炼（DashScope）聚合的第三方文本大模型：直接以模型 ID 调用，激活 bailian 即可用
  {
    id: 'bailian-deepseek-v4-pro',
    name: 'DeepSeek-V4-Pro（百炼）',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '百炼托管的 DeepSeek V4 Pro，激活百炼后直接调用，无需单独接入 DeepSeek。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'deepseek-v4-pro',
  },
  {
    id: 'bailian-deepseek-v4-flash',
    name: 'DeepSeek-V4-Flash（百炼）',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '百炼托管的 DeepSeek V4 Flash 高速版，激活百炼后直接调用。',
    latency: '2s',
    price: 0.002,
    currency: 'CNY',
    upstreamModel: 'deepseek-v4-flash',
  },
  {
    id: 'bailian-kimi-k3',
    name: 'Kimi-K3（百炼）',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '百炼托管的月之暗面 Kimi K3，激活百炼后直接调用（模型 ID 带 kimi/ 前缀）。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'kimi/kimi-k3',
  },
  {
    id: 'bailian-glm-5.2',
    name: '智谱 GLM-5.2（百炼）',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '百炼托管的智谱 GLM-5.2，激活百炼后直接调用。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'glm-5.2',
  },
  {
    id: 'bailian-minimax-m3',
    name: 'MiniMax-M3（百炼）',
    provider: 'bailian',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '百炼托管的 MiniMax M3，激活百炼后直接调用（模型 ID 带 MiniMax/ 前缀）。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'MiniMax/MiniMax-M3',
  },
  // 硅基流动（SiliconFlow）聚合的开源权重文本大模型：直接以 Vendor/Model 调用，激活 siliconflow 即可用
  {
    id: 'sf-deepseek-v3',
    name: 'DeepSeek-V3（硅基流动）',
    provider: 'siliconflow',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '硅基流动托管的 DeepSeek-V3 开源权重，激活 siliconflow 后直接调用。',
    latency: '3s',
    price: 0.001,
    currency: 'CNY',
    upstreamModel: 'deepseek-ai/DeepSeek-V3',
  },
  {
    id: 'sf-glm-4.6',
    name: '智谱 GLM-4.6（硅基流动）',
    provider: 'siliconflow',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '硅基流动托管的智谱 GLM-4.6 开源权重，激活 siliconflow 后直接调用。',
    latency: '3s',
    price: 0.002,
    currency: 'CNY',
    upstreamModel: 'ZhipuAI/GLM-4.6',
  },
  {
    id: 'sf-qwen3-235b',
    name: 'Qwen3-235B（硅基流动）',
    provider: 'siliconflow',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '硅基流动托管的 Qwen3-235B-A22B 开源权重，激活 siliconflow 后直接调用。',
    latency: '3s',
    price: 0.001,
    currency: 'CNY',
    upstreamModel: 'Qwen/Qwen3-235B-A22B',
  },
  {
    id: 'sf-minimax-text',
    name: 'MiniMax-Text-01（硅基流动）',
    provider: 'siliconflow',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '硅基流动托管的 MiniMax-Text-01 开源权重，激活 siliconflow 后直接调用。',
    latency: '3s',
    price: 0.002,
    currency: 'CNY',
    upstreamModel: 'MiniMaxAI/MiniMax-Text-01',
  },
  {
    id: 'sf-kimi-k2',
    name: 'Kimi-K2（硅基流动）',
    provider: 'siliconflow',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '硅基流动托管的月之暗面 Kimi-K2 开源权重，激活 siliconflow 后直接调用。',
    latency: '3s',
    price: 0.002,
    currency: 'CNY',
    upstreamModel: 'moonshotai/Kimi-K2',
  },
  // 火山方舟（Ark）聚合的第三方文本大模型：调用时 model 字段必须是「推理接入点 ID（ep-xxxx）」，
  // 因为 Ark 的推理 API 用 Bearer API Key，而接入点管理用 AccessKey/SecretKey + V4 签名（两套凭证）。
  // 激活 Ark 时若同时提供 AK/SK，后端会一键自动为每个模型创建接入点并缓存 ep-xxxx；
  // 仅提供推理 API Key 则需在控制台建好接入点后由下拉选择。requiresEndpoint=true 标记该约束。
  {
    id: 'volc-deepseek-v3',
    name: 'DeepSeek-V3（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟托管的 DeepSeek-V3。需先创建推理接入点，model 用接入点 ID（ep-xxxx）。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'deepseek-v3-241126',
    requiresEndpoint: true,
    endpointHint: '火山方舟需为每个模型创建推理接入点（控制台→模型广场→创建接入点），调用时 model 使用接入点 ID（ep-xxxx）。可在节点参数 endpointModel 填写你的接入点 ID。',
  },
  {
    id: 'volc-deepseek-r1',
    name: 'DeepSeek-R1（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟托管的 DeepSeek-R1 推理模型。需创建推理接入点，model 用接入点 ID。',
    latency: '4s',
    price: 0.02,
    currency: 'CNY',
    upstreamModel: 'deepseek-r1-250528',
    requiresEndpoint: true,
    endpointHint: '同 DeepSeek-V3：需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'volc-glm-4.6',
    name: '智谱 GLM-4.6（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟托管的智谱 GLM-4.6。需创建推理接入点，model 用接入点 ID。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'glm-4.6',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'volc-glm-4.5',
    name: '智谱 GLM-4.5（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟托管的智谱 GLM-4.5。需创建推理接入点，model 用接入点 ID。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'glm-4.5',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'volc-minimax-text',
    name: 'MiniMax-Text-01（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟托管的 MiniMax-Text-01。需创建推理接入点，model 用接入点 ID。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'MiniMax-Text-01',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'volc-kimi',
    name: 'Kimi（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟托管的月之暗面 Kimi（moonshot-v1-8k）。需创建推理接入点，model 用接入点 ID。',
    latency: '3s',
    price: 0.01,
    currency: 'CNY',
    upstreamModel: 'moonshot-v1-8k',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'volc-qwen3',
    name: 'Qwen3-235B（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟托管的 Qwen3-235B-A22B 开源权重。需创建推理接入点，model 用接入点 ID。',
    latency: '3s',
    price: 0.001,
    currency: 'CNY',
    upstreamModel: 'qwen3-235b-a22b',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'volc-seed-2.1-pro',
    name: 'Seed 2.1 Pro（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟自研 Seed 2.1 Pro 文本大模型，新用户免费额度。需创建推理接入点，model 用接入点 ID。',
    latency: '3s',
    price: 0,
    currency: 'CNY',
    discountLabel: '新用户免费',
    discountPercent: 100,
    upstreamModel: 'doubao-seed-2-1-pro',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。激活 Ark 时若提供 AK/SK 会自动建点。',
  },
  {
    id: 'volc-seed-2.1-turbo',
    name: 'Seed 2.1 Turbo（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟自研 Seed 2.1 Turbo 文本大模型，新用户免费额度，速度更快。需创建推理接入点。',
    latency: '2s',
    price: 0,
    currency: 'CNY',
    discountLabel: '新用户免费',
    discountPercent: 100,
    upstreamModel: 'doubao-seed-2-1-turbo',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'volc-seed-2.1-evolving',
    name: 'Seed 2.1 Evolving（火山方舟）',
    provider: 'volcengine',
    mode: 'llm',
    nodeTypes: ['text', 'script', 'storyboard', 'aiapp'],
    description: '火山方舟自研 Seed 2.1 Evolving 文本大模型，新用户免费额度，支持长上下文演进。需创建推理接入点。',
    latency: '3s',
    price: 0,
    currency: 'CNY',
    discountLabel: '新用户免费',
    discountPercent: 100,
    upstreamModel: 'doubao-seed-2-1-evolving',
    requiresEndpoint: true,
    endpointHint: '需在火山方舟创建推理接入点，model 用接入点 ID（ep-xxxx）。',
  },
  {
    id: 'wan22-t2v-a14b',
    name: 'Wan 2.2 文生视频',
    provider: 'siliconflow',
    mode: 'video',
    nodeTypes: ['video'],
    description: '硅基流动 Wan2.2 文生视频模型，适合广告短片与镜头预演',
    latency: '88s',
    price: 0.29,
    currency: 'USD',
    upstreamModel: 'Wan-AI/Wan2.2-T2V-A14B',
    capabilities: createVideoCapabilities({
      generationModes: ['textToVideo'],
      supportsTextToVideo: true,
      bestFor: ['文生视频预览', '广告分镜预演'],
      limitations: ['不支持主视频运镜锁定', '不支持身份控制器'],
    }),
  },
  {
    id: 'wan22-i2v-a14b',
    name: 'Wan 2.2 图生视频',
    provider: 'siliconflow',
    mode: 'video',
    nodeTypes: ['video'],
    description: '硅基流动 Wan2.2 图生视频模型，适合首尾帧、参考图和风格延展',
    latency: '95s',
    price: 0.29,
    currency: 'USD',
    upstreamModel: 'Wan-AI/Wan2.2-I2V-A14B',
    capabilities: createVideoCapabilities({
      generationModes: ['imageToVideo', 'firstLastFrame'],
      referenceRoles: ['style', 'subject', 'composition', 'lighting'],
      supportsMultiReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsImageToVideo: true,
      supportsFirstLastFrame: true,
      supportsReferenceImage: true,
      bestFor: ['图生视频', '首尾帧过渡', '风格延展'],
      limitations: ['不支持主视频运镜锁定', '不支持视频风格迁移'],
    }),
  },
  {
    id: 'bailian-wan22-t2v-plus',
    name: '百炼 Wan 2.2 文生视频',
    provider: 'bailian',
    mode: 'video',
    nodeTypes: ['video'],
    description: '阿里云百炼 Wan 2.2 文生视频模型，余额不足时自动回退到硅基流动 Wan2.2',
    latency: '90s',
    price: 1.4,
    currency: 'CNY',
    upstreamModel: 'wan2.2-t2v-plus',
    capabilities: createVideoCapabilities({
      generationModes: ['textToVideo'],
      supportsTextToVideo: true,
      bestFor: ['文生视频预览', '中文商业片草稿'],
      limitations: ['不支持主视频运镜锁定', '不支持身份控制器'],
    }),
  },
  {
    id: 'bailian-wan22-i2v-plus',
    name: '百炼 Wan 2.2 图生视频',
    provider: 'bailian',
    mode: 'video',
    nodeTypes: ['video'],
    description: '阿里云百炼 Wan 2.2 图生视频模型，支持参考图/首帧驱动视频生成',
    latency: '100s',
    price: 1.8,
    currency: 'CNY',
    upstreamModel: 'wan2.2-i2v-plus',
    capabilities: createVideoCapabilities({
      generationModes: ['imageToVideo', 'firstLastFrame'],
      referenceRoles: ['style', 'subject', 'composition', 'lighting'],
      supportsMultiReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsImageToVideo: true,
      supportsFirstLastFrame: true,
      supportsReferenceImage: true,
      bestFor: ['中文图生视频', '首尾帧生成'],
      limitations: ['不支持主视频运镜锁定', '不支持视频风格迁移'],
    }),
  },
  {
    id: 'seedance-v2',
    name: 'Seedance V2',
    provider: 'fal',
    mode: 'video',
    nodeTypes: ['video'],
    description: 'Image-to-video and camera motion.',
    latency: '55s',
    price: 2.8,
    currency: 'CNY',
    upstreamModel: 'doubao-seedance-2.0',
    capabilities: createVideoCapabilities({
      // 实测验证：APIMart relay 的 doubao-seedance-2.0 不支持 video_urls（HTTP 400）
      // 仅支持 imageToVideo / firstLastFrame (image_with_roles)
      generationModes: ['imageToVideo', 'firstLastFrame'],
      referenceRoles: ['style', 'subject', 'composition', 'lighting', 'omni'],
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsCameraMotionLockEnhancement: false,
      supportsIdentityController: true,
      supportsImageToVideo: true,
      supportsFirstLastFrame: true,
      supportsReferenceVideo: false,
      supportsReferenceImage: true,
      supportsVideoStyleTransfer: false,
      supportsPrimaryVideoMotionLock: false,
      supportsActionTransfer: false,
      bestFor: ['图生视频', '首尾帧控制', '主体一致性', '角色参考'],
    }),
  },
  {
    id: 'happyhorse-11',
    name: 'HappyHorse 1.1',
    provider: 'bailian',
    mode: 'video',
    nodeTypes: ['video'],
    description: 'Unified APIMart/Bailian video model that supports T2V, I2V, R2V, and edit style routing.',
    latency: '70s',
    price: 1.6,
    currency: 'CNY',
    upstreamModel: 'happyhorse-1.1',
    capabilities: createVideoCapabilities({
      generationModes: ['textToVideo', 'imageToVideo', 'referenceVideo', 'videoStyleTransfer'],
      referenceRoles: ['subject', 'style', 'composition', 'motion', 'omni'],
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsConsistencyEnhancement: true,
      supportsCameraMotionLockEnhancement: true,
      supportsTextToVideo: true,
      supportsImageToVideo: true,
      supportsReferenceVideo: true,
      supportsReferenceImage: true,
      supportsVideoStyleTransfer: true,
      supportsPrimaryVideoMotionLock: true,
      supportsActionTransfer: true,
      bestFor: ['多模态视频参考', '动作迁移', '视频编辑', '首帧驱动', '全能参数'],
    }),
  },
  {
    id: 'kling-v3-omni',
    name: 'Kling V3 Omni',
    provider: 'kling',
    mode: 'video',
    nodeTypes: ['video'],
    description: 'Primary-video-preserving multi-reference video editing with omni conditioning.',
    latency: '60s',
    price: 3,
    currency: 'CNY',
    upstreamModel: 'kling-v3-omni',
    discountLabel: 'Limited 9x',
    discountPercent: 10,
    capabilities: createVideoCapabilities({
      generationModes: ['textToVideo', 'imageToVideo', 'firstLastFrame', 'referenceVideo', 'videoStyleTransfer'],
      referenceRoles: ['style', 'subject', 'composition', 'lighting', 'motion', 'rhythm', 'omni'],
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsCameraMotionLockEnhancement: true,
      supportsIdentityController: true,
      supportsTextToVideo: true,
      supportsImageToVideo: true,
      supportsFirstLastFrame: true,
      supportsReferenceVideo: true,
      supportsReferenceImage: true,
      supportsVideoStyleTransfer: true,
      supportsPrimaryVideoMotionLock: true,
      supportsActionTransfer: true,
      bestFor: ['主体锁定', '主视频运镜保持', '动作迁移', '多参考换角', '全能参数'],
    }),
  },
  {
    id: 'kling-o3',
    name: 'Kling O3',
    provider: 'kling',
    mode: 'video',
    nodeTypes: ['video'],
    description: 'Realistic motion and first-last frame video.',
    latency: '60s',
    price: 3,
    currency: 'CNY',
    upstreamModel: 'kling-v3',
    discountLabel: 'Limited 9x',
    discountPercent: 10,
    capabilities: createVideoCapabilities({
      generationModes: ['textToVideo', 'imageToVideo', 'firstLastFrame', 'referenceVideo', 'videoStyleTransfer'],
      referenceRoles: ['style', 'subject', 'composition', 'lighting', 'motion', 'rhythm', 'omni'],
      supportsMultiReference: true,
      supportsOmniReference: true,
      supportsSubjectLock: true,
      supportsCompositionLock: true,
      supportsLightingControl: true,
      supportsConsistencyEnhancement: true,
      supportsCameraMotionLockEnhancement: true,
      supportsIdentityController: true,
      supportsTextToVideo: true,
      supportsImageToVideo: true,
      supportsFirstLastFrame: true,
      supportsReferenceVideo: true,
      supportsReferenceImage: true,
      supportsVideoStyleTransfer: true,
      supportsPrimaryVideoMotionLock: true,
      supportsActionTransfer: true,
      bestFor: ['主体锁定', '主视频运镜保持', '动作迁移', '高要求参考视频编辑', '全能参数'],
    }),
  },
];
